layers = [['u' * 30] * 16,
          ['u' * 30,
           'u' * 30,
           'u' * 30,
           'u' * 30,
           'u' * 30,
           'u' * 30,
           'uuuuuuunnnnnnnnnnnnnuuuuuuuuuu',
           'uuuuuuuouuuuuuuuuuumuuuuuuuuuu',
           'uuuuuuuouuuuuuuuuuumuuuuuuuuuu',
           'uuuuuuuouuuuuuuuuuumuuuuuuuuuu',
           'uuuuuuuouuuuuuuuuuumuuuuuuuuuu',
           'uuuuuuunnnnnnnnnnnnnuuuuuuuuuu',],
          ['u' * 30,
           'u' * 30,
           'u' * 30,
           'u' * 30,
           'u' * 30,
           'uuuuuuurrrrrrrrrrrrruuuuuuuuuu',
           '' * 30,
           '' * 30,
           '' * 30,
           '' * 30,
           'uuuuuuuorrrrrrrrrrrouuuuuuuuuu']]
